# Custom Language File for Launcher Customizer

[ejs.app]
title = "Emerald Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.tiktok.com/@gameofarkadia"
mediaXURL = "https://x.com/GameOfArkadia"
mediaInstagramURL = "https://www.instagram.com/gameofarkadia/"
mediaYouTubeURL = "https://www.youtube.com/@gameofarkadia"
mediaDiscordURL = "https://discord.gg/gameofarkadia"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/EmeraldLauncher"
supportLink = "https://github.com/dscalZi/EmeraldLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le launcher"
welcomeDescription = "Launcher non officiel et donc pas affilié a 'GameOfArkadia'"
welcomeDescCTA = "A quelque clics de rejoindre l'aventure"
